name: Deploy Minimal Fixed Root Site

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-minimal-root:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove ALL old project files
        run: |
          rm -rf * .github || true
          mkdir -p .github/workflows

      - name: Create JS files at root
        run: |
          echo "window.HELLO='Works!';" > hello.js

      - name: Create index.html at root
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="he" dir="rtl">
          <head>
            <meta charset="UTF-8">
            <title>בדיקת טעינה ABC</title>
            <script src="hello.js"></script>
          </head>
          <body>
            <h1 style="color:green">אתר עולה בהצלחה!</h1>
            <script>
              if (window.HELLO === 'Works!') {
                document.body.innerHTML += '<div style="color:blue">טעינת JS תקינה</div>';
              } else {
                document.body.innerHTML += '<div style="color:red">בעיה בטעינת JS</div>';
              }
            </script>
          </body>
          </html>
          EOF

      - name: Setup Github Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to Github Pages
        id: deploy
        uses: actions/deploy-pages@v4
