name: Deploy Interactive Games & Practice (ABC Explorer)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-interactive-games:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old project files
        run: |
          rm -rf * .github || true
          mkdir -p .github/workflows

      - name: Create public and games directories
        run: |
          mkdir -p public/games

      - name: Deploy games.js (game logic, practice types)
        run: |
          cat > public/games/games.js << 'EOF'
          // ABC English Explorer — Games & Practice Logic
          window.GAMES = {
            memory: { enabled: true, desc: "משחק זיכרון - התאמת זוגות", levels: ["A", "B", "C", "D", "E", "F"] },
            match: { enabled: true, desc: "משחק התאמה - מילה לתמונה/תרגום" },
            quiz:   { enabled: true, desc: "חידון רב-ברירה" },
            sentence: { enabled: true, desc: "בניית משפט נכון מהמילים ביחידה" }
            // ניתן להרחיב, דינמי לפי רמת כיתה/תגים
          }
          EOF

      - name: Deploy index.html (includes games logic)
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="he" dir="rtl">
          <head>
            <meta charset="UTF-8">
            <title>ABC Explorer - Practice & Games</title>
            <script src="public/content-pack.js"></script>
            <script src="public/games/games.js"></script>
          </head>
          <body>
            <h2>בודק - משחקי תרגול נטענים מהקבצים</h2>
            <pre id="gamedesc"></pre>
            <script>
              document.getElementById("gamedesc").textContent = 
                Object.keys(window.GAMES).map(
                  k => k + ": " + window.GAMES[k].desc
                ).join("\n");
            </script>
          </body>
          </html>
          EOF

      - name: Setup Github Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for Github Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to Github Pages
        id: deploy
        uses: actions/deploy-pages@v4
